location: gitman_sources
sources:
  - name: g.h
    type: git
    repo: git@github.com:mrpossoms/g.h.git
    sparse_paths:
      -
    rev: main
    link: deps/g.h 
  - name: json
    type: git
    repo: git@github.com:nlohmann/json.git
    sparse_paths:
      -
    rev: v3.10.4
sources_locked:
  - 
default_group: ''
groups:
  -

